<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/5_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices (Rank-2 Tensors)

In [1]:
import numpy as np

In [3]:
X = np.array([[25,2], [5, 26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [4]:
X.shape

(3, 2)

In [5]:
X.size

6

In [10]:
# if notation in left we can fetch the columns
X[:,0]


array([25,  5,  3])

In [11]:
# if notation in right we can fetch the rows
X[0,:]


array([25,  2])

In [13]:
X[2,:]

array([3, 7])

# PyTorch

In [14]:
import torch

In [15]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [27]:
X_pt[1,:]

tensor([ 5, 26])

# TensorFlow

In [17]:
import tensorflow as tf

In [18]:
X_tf = tf.Variable([[25,2], [5, 26], [3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [20]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [21]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>