<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/9_dot_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dot Product


In [1]:
import numpy as np
import torch
import tensorflow as tf

Numpy

In [3]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [5]:
np.dot(x,y)

32

PyTorch

In [6]:
x_pt = torch.tensor([1,2,3])
x

array([1, 2, 3])

In [7]:
y_pt = torch.tensor([4,5,6])
y_pt

tensor([4, 5, 6])

In [8]:
torch.dot(x_pt, y_pt)

tensor(32)

TensorFlow

In [9]:
x_tf = tf.Variable([1,2,3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [10]:
y_tf = tf.Variable([4,5,6])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [11]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=32>