<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/12_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
A = np.array([[3,4], [1,2], [5,1]])
A

array([[3, 4],
       [1, 2],
       [5, 1]])

In [4]:
b = np.array([1,2])
b

array([1, 2])

In [5]:
np.dot(A, b)

array([11,  5,  7])

In [6]:
A_pt = torch.tensor([[1,2], [3,4], [5,6]])
A_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [16]:
b_pt = torch.tensor([[1], [2]])
b_pt

tensor([[1],
        [2]])

In [17]:
torch.matmul(A_pt, b_pt)

tensor([[ 5],
        [11],
        [17]])