<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/2_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [3]:
# Rank 1 (1 dimensional) Tensor
x = np.array([1,5,10])
x

array([ 1,  5, 10])

In [6]:
len(x)

3

In [13]:
x.shape

(3,)

In [14]:
type(x)

numpy.ndarray

In [15]:
x[0]

1

# Vector Transposition

In [18]:
# Transposing a 1-D array has no effect
x_t = x.T
x_t

array([ 1,  5, 10])

In [20]:
x_t.shape
# result = (3,)

(3,)

In [21]:
# In order to transpose a 1-D vector write it in "matrix style" brackets
y = np.array([[23, 12, 2]])
y

array([[23, 12,  2]])

In [22]:
y.shape

(1, 3)

In [23]:
y_t = y.T
y_t

array([[23],
       [12],
       [ 2]])

In [25]:
y_t.shape
# result a column vector with 3 rows and 1 column

(3, 1)

In [28]:
# convert the transposed vector into the original vector
y_t.T

array([[23, 12,  2]])

In [31]:
y_t.T.shape
# a vector with 1 row and 3 column

(1, 3)

# Zero Vector

In [32]:
z = np.zeros(3);
z

array([0., 0., 0.])

# Vectors in PyTorch and Tensorflow

In [33]:
import torch
x_pt = torch.tensor([11, 13, 5])
x_pt

tensor([11, 13,  5])

In [35]:
import tensorflow as tf
x_tf = tf.Variable([12, 4])
x_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  4], dtype=int32)>