<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/8_tensor_reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Reduction
A tensor reduction is the sum of all elements of a tensor.

In [3]:
import torch
import numpy  as np
import tensorflow as tf

In [4]:
X = np.array([[1,2], [3,4], [5,6]])
X.sum()

tensor(21)

In [5]:
X_pt = torch.tensor([[1,2], [3,4], [5,6]])
torch.sum(X_pt)

tensor(21)

In [7]:
X_tf = tf.Variable([[1,2], [3,4], [5,6]])
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [8]:
# reduction such that an array of result is returned - axis-0 for adding rows and axis-1 for adding columns
X.sum(axis=0)

array([ 9, 12])

In [9]:
X.sum(axis=1)

array([ 3,  7, 11])