<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/norms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# L2 Norm OR Euclidean Norm

In [8]:
# create a 3 dimensional vector using numpy
import numpy as np
x = np.array([25,2,5])
x


array([25,  2,  5])

In [10]:
# Euclidean Norm
np.linalg.norm(x)

25.573423705088842

# L1 Norm

In [12]:
x

array([25,  2,  5])

In [14]:
np.abs(x[0]) + np.abs(x[1]) + np.abs(x[2])

32

# Squared L2 Norm

In [15]:
x

array([25,  2,  5])

In [16]:
(x[0]**2 + x[1]**2 + x[2]**2)

654

In [17]:
np.dot(x, x)

654

# Max Norm

In [19]:
x

array([25,  2,  5])

In [20]:
np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2])])

25