<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/symmetric_identity_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

# Symmetric Matrix

In [2]:
X_sym = np.array([[0,1,2], [1,7,8], [2,8,9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [3]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Identity Matrix
If we multiply Vector of length n with Identity Matrix the result is the same as the Vector of length n.

In [6]:
I = torch.tensor([[1,0,0], [0,1,0], [0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [7]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [8]:
torch.matmul(I, x_pt)

tensor([25,  2,  5])