<a href="https://colab.research.google.com/github/AhsenRiaz/Linear-Algebra-For-ML/blob/main/tensors-arithmetic-operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Arithmetic Operations

In [4]:
import torch

In [6]:
X_pt = torch.tensor([[1,2], [3,4], [5,6]])
X_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
X_pt+2

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [8]:
X_pt*2

tensor([[ 2,  4],
        [ 6,  8],
        [10, 12]])

In [9]:
X_pt*2+2

tensor([[ 4,  6],
        [ 8, 10],
        [12, 14]])

# Hadamard Product
In hadamard product we do operation on the correspondant element such that a1+v1 a2+v2 a3+v3. Same goes for multiplication

In [10]:
X_pt

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
Y_pt = X_pt + 2
Y_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [13]:
Z_pt = X_pt + Y_pt
Z_pt

tensor([[ 4,  6],
        [ 8, 10],
        [12, 14]])

In [14]:
A_pt = X_pt * Y_pt
A_pt

tensor([[ 3,  8],
        [15, 24],
        [35, 48]])